language: go
env:
  - TF_VERSION=0.10.1
  - TF_VERSION=0.10.2
  - TF_VERSION=0.10.3
  - TF_VERSION=0.10.4
  - TF_VERSION=0.10.5
  - TF_VERSION=0.10.6
  - TF_VERSION=0.10.7
  - TF_VERSION=0.10.8
  - TF_VERSION=0.11.0
  - TF_VERSION=0.11.1
  - TF_VERSION=0.11.2
  - TF_VERSION=0.11.3
  - TF_VERSION=0.11.4
  - TF_VERSION=0.11.5
  - TF_VERSION=0.11.6
  - TF_VERSION=0.11.7
  - TF_VERSION=0.11.8
  - TF_VERSION=0.11.9
  - TF_VERSION=0.11.10
  - TF_VERSION=0.11.11
  - TF_VERSION=0.11.12
  - TF_VERSION=0.11.13
  - TF_VERSION=0.11.14
  - TF_VERSION=0.12.0
  - TF_VERSION=0.12.1
  - TF_VERSION=0.12.2
  - TF_VERSION=0.12.3
  - TF_VERSION=0.12.4
  - TF_VERSION=0.12.5
  - TF_VERSION=0.12.6
  - TF_VERSION=0.12.7
  - TF_VERSION=0.12.8
  - TF_VERSION=0.12.9
before_install:
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
